project_name           = "weltspiel"
prod_project_id        = "fakeworld-prod-455516"
staging_project_id     = "fakeworld-staging-455516"
cicd_runner_project_id = "fakeworld-455516"
region                 = "europe-west3"
host_connection_name   = "git-Weltspiel"
repository_name        = "Weltspiel"
